#!/usr/bin/env python3
"""Send the final report via email."""

import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path


def send_report_email(
    report_path: str = "final_report.md",
    to_email: str = None,
    from_email: str = None,
    password: str = None,
    smtp_server: str = "smtp.gmail.com",
    smtp_port: int = 587,
):
    """Send the final report via email.

    Uses environment variables for email configuration if not provided as arguments.
    """
    # Get configuration from environment or arguments
    to_email = to_email or os.environ.get("EMAIL_TO", "fabio.pettian@gmail.com")
    from_email = from_email or os.environ.get("EMAIL_FROM")
    password = password or os.environ.get("EMAIL_PASSWORD")
    smtp_server = smtp_server or os.environ.get("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.environ.get("SMTP_PORT", smtp_port))

    if not from_email or not password:
        print("Warning: EMAIL_FROM or EMAIL_PASSWORD not set. Email will not be sent.")
        print("To send emails, set these secrets in your GitHub repository:")
        print("  - EMAIL_FROM: Sender email address")
        print("  - EMAIL_PASSWORD: App password for the sender email")
        print("  - SMTP_SERVER: SMTP server (default: smtp.gmail.com)")
        print("  - SMTP_PORT: SMTP port (default: 587)")
        return False

    # Read the report
    report_file = Path(report_path)
    if not report_file.exists():
        print(f"Error: Report file not found: {report_path}")
        return False

    report_content = report_file.read_text(encoding="utf-8")
    today = datetime.now().strftime("%Y-%m-%d")

    # Create email message
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Daily AI Engineer Scout Report - {today}"
    msg["From"] = from_email
    msg["To"] = to_email

    # Create plain text version (strip markdown)
    text_content = report_content.replace("# ", "").replace("## ", "").replace("**", "")

    # Create HTML version
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            h2 {{ color: #34495e; margin-top: 30px; }}
            ul {{ padding-left: 20px; }}
            li {{ margin-bottom: 8px; }}
            a {{ color: #3498db; text-decoration: none; }}
            a:hover {{ text-decoration: underline; }}
            .header {{ background: #f8f9fa; padding: 20px; border-radius: 5px; margin-bottom: 30px; }}
            .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #666; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🤖 Remote AI Engineer Scout</h1>
            <p>Daily report generated on {today}</p>
        </div>
        {markdown_to_html(report_content)}
        <div class="footer">
            <p>This report was automatically generated by <a href="https://github.com/{os.environ.get('GITHUB_REPOSITORY', 'your-repo')}">Remote AI Engineer Scout</a></p>
            <p>To unsubscribe, disable the GitHub Actions workflow in your repository settings.</p>
        </div>
    </body>
    </html>
    """

    # Attach parts
    part1 = MIMEText(text_content, "plain", "utf-8")
    part2 = MIMEText(html_content, "html", "utf-8")
    msg.attach(part1)
    msg.attach(part2)

    # Also attach the markdown file
    attachment = MIMEText(report_content, "plain", "utf-8")
    attachment.add_header(
        "Content-Disposition",
        f"attachment; filename=ai_engineer_report_{today}.md"
    )
    msg.attach(attachment)

    # Send email
    try:
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(from_email, password)
        server.sendmail(from_email, to_email, msg.as_string())
        server.quit()
        print(f"✅ Email sent successfully to {to_email}")
        return True
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return False


def markdown_to_html(markdown_text: str) -> str:
    """Simple markdown to HTML conversion."""
    html = markdown_text

    # Headers
    html = html.replace("# ", "<h1>", 1).replace("\n# ", "</p><h1>", 1)
    html = html.replace("\n## ", "</p><h2>")
    html = html.replace("\n### ", "</p><h3>")

    # Bold
    html = html.replace("**", "<strong>", 1)
    html = html.replace("**", "</strong>", 1)

    # Lists
    lines = html.split("\n")
    result = []
    in_list = False

    for line in lines:
        if line.strip().startswith("- ") or line.strip().startswith("* "):
            if not in_list:
                result.append("<ul>")
                in_list = True
            content = line.strip()[2:]
            # Handle bold in list items
            content = content.replace("**", "<strong>", 1).replace("**", "</strong>", 1)
            result.append(f"<li>{content}</li>")
        else:
            if in_list:
                result.append("</ul>")
                in_list = False
            if line.strip():
                # Handle links
                import re
                line = re.sub(
                    r'\[([^\]]+)\]\(([^)]+)\)',
                    r'<a href="\2">\1</a>',
                    line
                )
                result.append(f"<p>{line}</p>")

    if in_list:
        result.append("</ul>")

    return "".join(result)


if __name__ == "__main__":
    success = send_report_email()
    exit(0 if success else 1)
